{{- if eq (include "portal.secret.inline.enabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.keycloakClientSecret }}
  {{ include "portal.secret.key.keycloakClientSecret" . }}: {{ include "portal.secret.value.keycloakClientSecret" . | quote }}
  {{- end }}
  {{- if .Values.auth.keycloakRealm }}
  {{ include "portal.secret.key.keycloakRealm" . }}: {{ include "portal.secret.value.keycloakRealm" . | quote }}
  {{- end }}
{{- end }}
