apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort.enabled }}
      nodePort: {{ .Values.service.nodePort.port }}
      {{- end }}
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
