import { useTranslation } from "react-i18next";
import { Bot, User } from "lucide-react";
import { MessageContent } from "./message-content";
import { ThinkingBlock } from "./thinking-block";
import { ToolCallCard } from "./tool-call-card";
import { BlockReplyBubble } from "./block-reply-bubble";
import { MediaGallery } from "./media-gallery";
import { useUiStore } from "@/stores/use-ui-store";
import { resolveTimezone } from "@/lib/format";
import type { ChatMessage } from "@/types/chat";

interface MessageBubbleProps {
  message: ChatMessage;
  /**
   * When true, renders a blurred skeleton placeholder below the message
   * content indicating that an image is currently being generated.
   * Used by ActiveRunZone during streaming when the agent uses a
   * provider that supports native image generation.
   */
  showImageGenPlaceholder?: boolean;
}

/** Skeleton block shown while an image is being generated by the assistant. */
function ImageGenPlaceholder() {
  const { t } = useTranslation("chat");
  return (
    <div className="mt-2 flex flex-col gap-1.5">
      {/* Blurred square mimicking an image preview */}
      <div className="h-40 w-full max-w-[240px] rounded-lg bg-muted animate-pulse overflow-hidden relative">
        <div className="absolute inset-0 backdrop-blur-sm" />
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-muted-foreground border-t-transparent" />
        </div>
      </div>
      <span className="text-xs text-muted-foreground">{t("imageGenGenerating")}</span>
    </div>
  );
}

export function MessageBubble({ message, showImageGenPlaceholder = false }: MessageBubbleProps) {
  const timezone = useUiStore((s) => s.timezone);
  const isUser = message.role === "user";
  const isTool = message.role === "tool";

  if (isTool) return null;
  if (message.isNotification) return null;
  if (message.isBlockReply) return <BlockReplyBubble message={message} />;

  const isAssistant = message.role === "assistant";
  const hasThinking = isAssistant && !!message.thinking;
  const hasToolDetails = isAssistant && message.toolDetails && message.toolDetails.length > 0;
  const hasToolCalls = isAssistant && message.tool_calls && message.tool_calls.length > 0;
  const hasContent = !!message.content?.trim();

  if (isAssistant && !hasContent && !hasToolCalls && !hasToolDetails) return null;

  // Tool-only message (no text content) — render compact without bubble wrapper
  const isToolOnly = isAssistant && !hasContent && !hasThinking && (hasToolDetails || hasToolCalls);

  return (
    <div className={`flex gap-3 ${isUser ? "flex-row-reverse" : ""}`}>
      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border bg-background">
        {isUser ? <User className="h-4 w-4" /> : <Bot className="h-4 w-4" />}
      </div>

      {isToolOnly ? (
        /* Compact tool-only card — no bubble wrapper, full width */
        <div className="flex-1 min-w-0 rounded-md border bg-muted divide-y divide-border">
          {hasThinking && (
            <div className="px-2 py-1.5">
              <ThinkingBlock text={message.thinking!} />
            </div>
          )}
          {hasToolDetails && message.toolDetails!.map((entry) => (
            <ToolCallCard key={entry.toolCallId} entry={entry} compact />
          ))}
        </div>
      ) : (
        /* Normal message bubble — assistant uses full width, user capped at 85% */
        <div className={`rounded-lg px-4 py-2 ${
          isUser
            ? "max-w-[85%] bg-card text-card-foreground border border-border shadow-sm border-r-2 border-r-accent-foreground"
            : "flex-1 min-w-0 bg-card text-card-foreground border border-border shadow-sm"
        }`}>
          {hasThinking && (
            <div className="mb-2">
              <ThinkingBlock text={message.thinking!} />
            </div>
          )}
          {hasToolDetails && (
            <div className="mb-2 rounded-md border bg-muted divide-y divide-border">
              {message.toolDetails!.map((entry) => (
                <ToolCallCard key={entry.toolCallId} entry={entry} compact />
              ))}
            </div>
          )}
          <MessageContent content={message.content} role={message.role} mediaBasenames={message.mediaItems?.map((m) => m.path.split("/").pop() ?? "").filter(Boolean)} />
          {message.mediaItems && message.mediaItems.length > 0 && (
            <div className="mt-2">
              <MediaGallery items={message.mediaItems} />
            </div>
          )}
          {/* Image-gen placeholder: shown during streaming when the provider supports
              native image generation and no final image has arrived yet. Replaced by
              MediaGallery once run.completed delivers the actual MediaRef. */}
          {showImageGenPlaceholder && <ImageGenPlaceholder />}
          {message.timestamp && (
            <div className="mt-1 text-2xs text-muted-foreground">
              {new Intl.DateTimeFormat([], {
                timeZone: resolveTimezone(timezone),
                hour: "numeric",
                minute: "2-digit",
              }).format(new Date(message.timestamp))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
