{{- if eq (include "postgresql.secret.inline.enabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: '{{ include "postgresql.chart" . }}'
    app.kubernetes.io/name: '{{ include "postgresql.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
type: Opaque
stringData:
  {{ include "postgresql.secret.key.postgresPassword" . }}: {{ include "postgresql.secret.value.postgresPassword" . | quote }}
  {{ include "postgresql.secret.key.replicationPassword" . }}: {{ include "postgresql.secret.value.replicationPassword" . | quote }}
{{- end }}
