{{- if eq (include "cloudflared.secret.inline.enabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "cloudflared.secret.key.tunnelToken" . }}: {{ include "cloudflared.secret.value.tunnelToken" . | quote }}
{{- end }}
